version: '3'
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=dbportfolio
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=iamroot
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306